sudo: false
git:
    depth: 1
language: php
php:
    - 5.4
    - 5.5
    - 7.0
    - 7.1
matrix:
    include:
        - php: 5.6
          env:
              - PHPUNIT_COVERAGE="--coverage-clover=coverage.xml"
cache:
    directories:
        - vendor
before_install:
    - stty cols 120
    - |
      if [ -z "$PHPUNIT_COVERAGE" ]; then
          phpenv config-rm xdebug.ini
      fi
install:
    - composer self-update
    - composer config -g repositories.asset-packagist composer https://asset-packagist.org
    - travis_retry composer update --no-interaction --prefer-stable --prefer-dist
    - composer show
script:
    - vendor/bin/phpunit $PHPUNIT_COVERAGE
after_success:
    - |
      if [ -n "$PHPUNIT_COVERAGE" ]; then
          travis_retry wget https://codecov.io/bash
          bash ./bash
      fi
after_script:
    - |
      if [ -n "$PHPUNIT_COVERAGE" ]; then
          travis_retry wget https://scrutinizer-ci.com/ocular.phar
          php ocular.phar code-coverage:upload --format=php-clover coverage.xml
      fi
